### ISSUE TITLE
I have a quesion about the  condconv mentioned.

### ISSUE THREAD

**Issue by zwhyOuO** [summitgao/SAR_CD_SAFNet#5]
For the convolution mentioned in the article, I did not find the corresponding part in the code you provided. In the multi-scale features extraction part, it is mentioned in the article that the routing weights is used, but in the code, normal convolution is used to extract features, there is no routing weights.

**Comment by summitgao** [comment]
The student responsible for the code has graduated. Maybe he upload the wrong version of code. We will check the codes carefully recently. 

> For the convolution mentioned in the article, I did not find the corresponding part in the code you provided. In the multi-scale features extraction part, it is mentioned in the article that the routing weights is used, but in the code, normal convolution is used to extract features, there is no routing weights.

**Comment by zwhyOuO** [comment]
> The student responsible for the code has graduated. Maybe he upload the wrong version of code. We will check the codes carefully recently.
> 
> > For the convolution mentioned in the article, I did not find the corresponding part in the code you provided. In the multi-scale features extraction part, it is mentioned in the article that the routing weights is used, but in the code, normal convolution is used to extract features, there is no routing weights.

That would be great. Thank you very much
